### PR TITLE
Ch20323/right click context menu

### PR DESCRIPTION
**Pull request by SamueleA**
-Added right click menu
-Trash and rename option is missing. Trash can be added when integrated
-Folders cannot be shared for now

Screenshot from 2020-11-26 10-21-59

Peek 2020-11-26 12-18

### CODE REVIEW

**Comment by gpuente** [comment]
@SamueleA can you point this PR to a new feature branch please? prob tomorrow we are going to do a new FE release and I think this feature should not be included until we have all the integrations done

**Comment by morochroyce** [comment]
@Blockchainbrett are we positive these are the only ones we are doing for now?

**Comment by SamueleA** [comment]
@morochroyce 
we are adding the delete once it is integrated. For rename, we still do not have a method on the daemon yet. So for now, only open and share is ready

**Comment by SamueleA** [comment]
@morochroyce 
closing this PR since https://github.com/FleekHQ/space-desktop/pull/375 is built on top of it. It contains right click + integration for the delete action. Let's continue discussions there.

**Pull request closed without merging**
