### PR TITLE
Ch20310/table ui visual updates

### PR DESCRIPTION
**Pull request by SamueleA**
1. Remove hours, minutes, seconds from date
2. new visual for selected, hover and error (error not integrated in this card).
3. Added icon next to file to show the state green = space, gray = space, but not local, spinner = syncing

Peek 2020-11-30 15-47

Peek 2020-11-30 15-39

error state is there, but not integrated
Screenshot from 2020-11-30 15-43-01

### CODE REVIEW

**Comment by morochroyce** [comment]
are we going to be changing the background to white instead of gray? it doesnt look great right now the gray background. is that something quick you are able to do?

**Comment by SamueleA** [comment]
@morochroyce I replaced the blue with a white background

image

Also, added @mateuszJS cell component to the table

**Comment by morochroyce** [comment]
can we get rid of the icon system on the right

**Review by giankotarola — APPROVED** [review]

**Comment by SamueleA** [comment]
> can we get rid of the icon system on the right. also can we spread the columns further apart from each other like it is in the new ui. and make the search bar the gray we use in new designs.

We can make those changes on another PR. This PR is for the updates to the rows with hovers, etc... We have other cards still so we have more changes coming

**Comment by gpuente** [comment]
@SamueleA the row border are going to be included on this PR as well?

**Comment by gpuente** [comment]
@SamueleA I think that the "Size" header has a left padding, so the the "Size" is aligned with the size values and not the icon

**Comment by SamueleA** [comment]
@gpuente I fixed the size header and the row borders in 392eaf8

**Pull request merged**
