### PR TITLE
Mateuszwalendzik/ch20099/update design of sharing modal visual only

### PR DESCRIPTION
**Pull request by mateuszJS**
Screenshot 2020-11-23 at 13 18 40

### CODE REVIEW

**Review by SamueleA — APPROVED** [review]

**Comment by morochroyce** [comment]
can we make sure the shadow is the correct style on the modal? it looks a bit too dense.

**Comment by mateuszJS** [comment]
> can we make sure the shadow is the correct style on the modal? it looks a bit too dense.

@morochroyce fixed
image

**Comment by morochroyce** [comment]
Im pretty sure we can get rid of that can edit stuff, does it even work for the app? also, the rounding of the rainbow outline doesnt look right, the inner white isnt rounded enough to match the rainbow thickness. The shadowing I was talking about is the entire modal, if you look in the PR picture at the bottom it shows like a black line as thick and dark shadowing. We don't have that, please check the design again. Also this shadow is applied to the dropdown list, it doesnt look good. And the dropdown box should be the same exact length as the input.

**Review by gpuente — APPROVED** [review]
LGTM

**Pull request merged**
