### PR TITLE
Redirect to shared-by route after accept shared file

### PR DESCRIPTION
**Pull request by gpuente**
## Changelog

- Redirect to shared-by route after accept shared file
- Handle loading state before redirect

### CODE REVIEW

**Comment by SamueleA** [comment]
I believe this change will also require showing a loading state when rejecting or accepting. iirc we just write to the cache to make the accept/reject show quicker, but if we redirect that redirect might happen several seconds later or more depending if the file is very large.

**Review by mateuszJS — APPROVED** [review]

**Comment by gpuente** [comment]
@SamueleA you're right, going to handle the loading state

**Comment by gpuente** [comment]
@SamueleA I've added the changes that you mentioned. Would be great if you can review it again

**Comment by SamueleA** [comment]
lgtm

**Review by SamueleA — APPROVED** [review]

**Pull request merged**
